package ru.adiaphora.platform.document.infrastructure;

import org.springframework.stereotype.Component;
import ru.adiaphora.platform.document.domain.DocumentData;
import ru.adiaphora.platform.document.domain.DocumentGenerator;
import ru.adiaphora.platform.document.domain.DocumentTemplate;
import ru.adiaphora.platform.document.domain.GeneratedDocumentContent;

import java.nio.charset.StandardCharsets;

/**
 * Placeholder {@link DocumentGenerator} that emits a simple text stub — enough to exercise the
 * request/store/download flow. Real DOCX/PDF generation replaces this behind the same interface, and
 * the produced content must be reviewed by a lawyer before any real use.
 */
@Component
class PlaceholderDocumentGenerator implements DocumentGenerator {

    @Override
    public GeneratedDocumentContent generate(DocumentTemplate template, DocumentData data) {
        String filename = template.filenamePattern()
                .replace("{applicationId}", data.applicationId().toString());
        String body = """
                PLACEHOLDER DOCUMENT — NOT A REAL LEGAL DOCUMENT
                Template: %s (%s)
                Application: %s
                Generated by the Adiaphora platform for development purposes only.
                """.formatted(template.name(), template.code(), data.applicationId());
        return new GeneratedDocumentContent(filename, template.contentType(),
                body.getBytes(StandardCharsets.UTF_8));
    }
}
